# Generated by Django 4.1.2 on 2023-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodname', models.CharField(max_length=255, null=True)),
                ('Foodcost', models.CharField(max_length=255, null=True)),
                ('Foodtype', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
