# Generated by Django 4.1.2 on 2023-06-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Foodcost',
            new_name='foodcost',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Foodname',
            new_name='foodname',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Foodtype',
            new_name='foodtype',
        ),
    ]
